try{
  let a;
  console.log(a.length);
  // if there is an error in the try statement then the control reaches in catch
}
catch(e) {
  console.log("control reached inside catch");
}
//try catch syntax
console.log("hello")
